# Generated by Django 3.2.2 on 2021-05-18 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image_upload',
        ),
    ]
