# Generated by Django 3.2.2 on 2021-05-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_image_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_upload',
            name='image',
            field=models.URLField(),
        ),
    ]
