# Generated by Django 3.2.3 on 2021-05-18 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadimage_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='caption',
            new_name='title',
        ),
    ]
