# Generated by Django 3.2.2 on 2021-05-18 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadimage_app', '0002_rename_caption_image_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
